/**************************************************************
 * This file is generated by a T4 template. regenerate it by 
 * right-clicking on the .tt file in solution explorer
 * and clicking "Run Custom Tool"
 **************************************************************/

namespace BBQRMSSolution.ServerProxy
{
	public class DinerTypes
	{
		public const int DineIn = 1;
		public const int CarryOut = 2;
		public const int Delivery = 3;
	}
	public class OrderStates
	{
		public const int Cooking = 1;
		public const int Cancelled = 2;
		public const int Completed = 3;
		public const int Saved = 4;
		public const int InProgress = 5;
		public const int Closed = 6;
	}
	public class OrderTypes
	{
		public const int Phone = 1;
		public const int WalkIn = 2;
		public const int Website = 3;
	}
	public class PaymentStates
	{
		public const int Unpaid = 1;
		public const int PartiallyPaid = 2;
		public const int Paid = 3;
	}
	public class PaymentTypes
	{
		public const int Cash = 1;
		public const int CreditCard = 2;
		public const int Check = 3;
	}
	public class Privileges
	{
		public const int TakeOrders = 1;
		public const int Cashier = 2;
		public const int UseCooksScreen = 3;
		public const int UseQuickInventory = 4;
		public const int RunReports = 5;
		public const int ManageEmployees = 6;
		public const int ManageInventory = 7;
		public const int ManageMenus = 8;
		public const int OpenAdmin = 9;
	}
	public class ConsumptionTypes
	{
		public const int Used = 1;
		public const int Wasted = 2;
	}
}

